# Generated by Django 5.1.6 on 2025-02-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('Oxygen Shortage', 'Oxygen Shortage'), ('Bed Full', 'Bed Full'), ('Food Shortage', 'Food Shortage'), ('Water Shortage', 'Water Shortage'), ('Medical Shortage', 'Medical Shortage'), ('Volunteer Required', 'Volunteer Required'), ('Transport Required', 'Transport Required'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.CharField(max_length=255)),
                ('total_beds', models.IntegerField()),
                ('available_beds', models.IntegerField()),
                ('icu_beds', models.IntegerField()),
                ('ventilators', models.IntegerField()),
                ('oxygen_supply', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReliefCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.CharField(max_length=255)),
                ('food_stock', models.IntegerField()),
                ('water_stock', models.IntegerField()),
                ('medical_stock', models.IntegerField()),
                ('volunteer_count', models.IntegerField()),
                ('transport_count', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('location_link', models.CharField(max_length=255)),
                ('total_capacity', models.IntegerField()),
                ('available_capacity', models.IntegerField()),
                ('food_stock', models.IntegerField()),
                ('water_stock', models.IntegerField()),
                ('medical_stock', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
