# Generated by Django 5.1.6 on 2025-02-16 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_resource_supplier_supplychainlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrisisEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Fire', 'Fire'), ('Medical Emergency', 'Medical Emergency'), ('Resource Shortage', 'Resource Shortage'), ('Pandemic', 'Pandemic'), ('Other', 'Other')], max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('severity', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SafetyInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crisis_type', models.CharField(choices=[('Earthquake', 'Earthquake'), ('Flood', 'Flood'), ('Fire', 'Fire'), ('Medical Emergency', 'Medical Emergency'), ('Resource Shortage', 'Resource Shortage'), ('Pandemic', 'Pandemic'), ('Other', 'Other')], max_length=50)),
                ('dos', models.TextField()),
                ('donts', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=15, unique=True)),
                ('is_vendor', models.BooleanField(default=False)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='alert',
            name='alert_type',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='location_link',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='alert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alert',
            name='crisis_event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='api.crisisevent'),
            preserve_default=False,
        ),
    ]
